default_language_version:
  python: python3

ci:
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
  autoupdate_schedule: quarterly
  # submodules: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-docstring-first
      # - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=350', '--enforce-all']
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
        name: Upgrade code

  - repo: https://github.com/myint/docformatter
    rev: v1.5.1
    hooks:
      - id: docformatter
        args: [--in-place]

  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        name: Unused noqa

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Format imports

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Format code
        exclude: docs/source-app

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          #- mdformat-black
          - mdformat_frontmatter

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Check PEP8
